defaults:
  - _self_

paths:
  input_videos_dir: data/original_inputs
  csv_output_dir: data/CSV_stage_1
  final_csv_path: data/final_dataset.csv

filters:
  min_body_height_ratio: 0.35
  max_body_height_ratio: 0.75
  min_frame_segment: 120
  min_frame: 120

mediapipe:
  model_complexity: 1
  min_detection_confidence: 0.5
  min_tracking_confidence: 0.5